// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

if (process.env.DATABASE_URL) {
  const url = process.env.DATABASE_URL;
  if (!/sslmode=/.test(url)) {
    process.env.DATABASE_URL = url;
  }
}

if (process.env.DIRECT_DATABASE_URL) {
  const url = process.env.DIRECT_DATABASE_URL;
  if (!/sslmode=/.test(url)) {
    process.env.DIRECT_DATABASE_URL = url;
  }
}

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: process.env.DIRECT_DATABASE_URL || process.env.DATABASE_URL,
  },
});
